"""Hand-picked levelled curriculum for Jyut Dictation.

Each row is (level, category, traditional, english) with an optional fifth field
pinning a reading. The English gloss is written for a learner — short and
single-sense — because raw dictionary glosses are often long lists of senses. The
Jyutping and simplified forms are NEVER written here: build_vocab.py takes those
from CC-Canto so every reading is dictionary-sourced.

The pinned reading exists only for polyphones, where frequency ranking picks a
rare sense over the everyday one (行 hang4 "a row" vs haang4 "to walk"). It
selects among the dictionary's own readings and build_vocab.py fails if the
pinned reading is not attested there, so it is a choice, not an invention.

Levels loosely map to CEFR A1-C1 and follow the counts common Cantonese course
platforms use: 40 / 50 / 50 / 43 / 36 / 28 = 247 entries.
"""

LEVEL_NAMES = {
    1: "Absolute Beginner",
    2: "Beginner",
    3: "Elementary",
    4: "Intermediate",
    5: "Upper-Intermediate",
    6: "Advanced",
}

LEVEL_DESCRIPTIONS = {
    1: "Your first words: greetings, numbers, family and the verbs you use every day.",
    2: "Asking questions, telling the time, colours, places and everyday courtesies.",
    3: "Classifiers, the body, weather, money, directions and daily routine.",
    4: "Feelings, work and study, describing things, and joining ideas together.",
    5: "Abstract nouns, society, opinions and the phrases that make you sound natural.",
    6: "Idioms, formal written vocabulary, discourse markers and advanced slang.",
}

CURRICULUM: list[tuple[int, str, str, str] | tuple[int, str, str, str, str]] = [
    # ------------------------------------------------------------------ Level 1
    (1, "Greetings", "你好", "hello"),
    (1, "Greetings", "早晨", "good morning"),
    (1, "Greetings", "再見", "goodbye"),
    (1, "Greetings", "拜拜", "bye-bye"),
    (1, "Greetings", "唔該", "thanks / excuse me"),
    (1, "Greetings", "多謝", "thank you (for a gift)"),
    (1, "Numbers", "零", "zero"),
    (1, "Numbers", "一", "one"),
    (1, "Numbers", "二", "two"),
    (1, "Numbers", "三", "three"),
    (1, "Numbers", "四", "four"),
    (1, "Numbers", "五", "five"),
    (1, "Numbers", "六", "six"),
    (1, "Numbers", "七", "seven"),
    (1, "Numbers", "八", "eight"),
    (1, "Numbers", "九", "nine"),
    (1, "Numbers", "十", "ten"),
    (1, "Pronouns", "我", "I / me"),
    (1, "Pronouns", "你", "you"),
    (1, "Pronouns", "佢", "he / she / it", "keoi5"),
    (1, "Pronouns", "我哋", "we / us"),
    (1, "Pronouns", "你哋", "you (plural)"),
    (1, "Yes & No", "係", "to be / yes"),
    (1, "Yes & No", "唔係", "is not / no"),
    (1, "Yes & No", "好", "good"),
    (1, "Yes & No", "冇", "to not have"),
    (1, "Family", "媽媽", "mother"),
    (1, "Family", "爸爸", "father"),
    (1, "Family", "哥哥", "elder brother"),
    (1, "Family", "姐姐", "elder sister"),
    (1, "Family", "弟弟", "younger brother"),
    (1, "Family", "妹妹", "younger sister"),
    (1, "Food & Drink", "水", "water"),
    (1, "Food & Drink", "茶", "tea"),
    (1, "Food & Drink", "飯", "rice / a meal"),
    (1, "Food & Drink", "麵", "noodles"),
    (1, "Food & Drink", "咖啡", "coffee"),
    (1, "Common Verbs", "食", "to eat"),
    (1, "Common Verbs", "飲", "to drink"),
    (1, "Common Verbs", "去", "to go"),
    # ------------------------------------------------------------------ Level 2
    (2, "Question Words", "乜嘢", "what"),
    (2, "Question Words", "邊度", "where"),
    (2, "Question Words", "邊個", "who / which one"),
    (2, "Question Words", "幾時", "when"),
    (2, "Question Words", "點解", "why"),
    (2, "Question Words", "點樣", "how"),
    (2, "Question Words", "幾多", "how many / how much"),
    (2, "Colours", "紅色", "red"),
    (2, "Colours", "藍色", "blue"),
    (2, "Colours", "綠色", "green"),
    (2, "Colours", "黃色", "yellow"),
    (2, "Colours", "黑色", "black"),
    (2, "Colours", "白色", "white"),
    (2, "Colours", "紫色", "purple"),
    (2, "Time", "今日", "today"),
    (2, "Time", "聽日", "tomorrow"),
    (2, "Time", "尋日", "yesterday"),
    (2, "Time", "而家", "now"),
    (2, "Time", "星期", "week"),
    (2, "Time", "月", "month / moon"),
    (2, "Time", "年", "year"),
    (2, "Time", "點鐘", "o'clock"),
    (2, "Places", "屋企", "home"),
    (2, "Places", "學校", "school"),
    (2, "Places", "餐廳", "restaurant"),
    (2, "Places", "醫院", "hospital"),
    (2, "Places", "銀行", "bank"),
    (2, "Places", "商店", "shop"),
    (2, "Places", "街市", "wet market"),
    (2, "Food & Drink", "牛肉", "beef"),
    (2, "Food & Drink", "豬肉", "pork"),
    (2, "Food & Drink", "雞", "chicken"),
    (2, "Food & Drink", "魚", "fish", "jyu4"),
    (2, "Food & Drink", "菜", "vegetable"),
    (2, "Food & Drink", "生果", "fruit"),
    (2, "Food & Drink", "雞蛋", "egg"),
    (2, "Common Verbs", "睇", "to look / to watch"),
    (2, "Common Verbs", "聽", "to listen"),
    (2, "Common Verbs", "講", "to speak"),
    (2, "Common Verbs", "買", "to buy"),
    (2, "Common Verbs", "賣", "to sell"),
    (2, "Common Verbs", "做", "to do / to make"),
    (2, "Common Verbs", "嚟", "to come"),
    (2, "Common Verbs", "行", "to walk", "haang4"),
    (2, "Everyday Phrases", "對唔住", "sorry"),
    (2, "Everyday Phrases", "唔緊要", "never mind"),
    (2, "Everyday Phrases", "唔好意思", "excuse me / sorry"),
    (2, "Everyday Phrases", "冇問題", "no problem"),
    (2, "Everyday Phrases", "好耐冇見", "long time no see"),
    (2, "Everyday Phrases", "點呀", "how's it going?"),
    # ------------------------------------------------------------------ Level 3
    (3, "Classifiers", "個", "general classifier"),
    (3, "Classifiers", "隻", "classifier for animals"),
    (3, "Classifiers", "張", "classifier for flat things"),
    (3, "Classifiers", "本", "classifier for books"),
    (3, "Classifiers", "杯", "classifier for cups / a cup"),
    (3, "Classifiers", "件", "classifier for items / clothes"),
    (3, "Classifiers", "條", "classifier for long things"),
    (3, "Body & Health", "頭", "head"),
    (3, "Body & Health", "手", "hand"),
    (3, "Body & Health", "腳", "foot / leg"),
    (3, "Body & Health", "眼", "eye"),
    (3, "Body & Health", "口", "mouth"),
    (3, "Body & Health", "肚", "belly"),
    (3, "Body & Health", "病", "illness / to be ill"),
    (3, "Weather", "天氣", "weather"),
    (3, "Weather", "落雨", "to rain"),
    (3, "Weather", "熱", "hot"),
    (3, "Weather", "凍", "cold"),
    (3, "Weather", "太陽", "sun"),
    (3, "Weather", "風", "wind"),
    (3, "Money & Shopping", "錢", "money"),
    (3, "Money & Shopping", "幾錢", "how much does it cost?"),
    (3, "Money & Shopping", "平", "cheap", "peng4"),
    (3, "Money & Shopping", "貴", "expensive"),
    (3, "Money & Shopping", "找錢", "to give change"),
    (3, "Money & Shopping", "買嘢", "to go shopping"),
    (3, "Money & Shopping", "收銀", "cashier"),
    (3, "Directions", "左邊", "left side"),
    (3, "Directions", "右邊", "right side"),
    (3, "Directions", "前面", "in front"),
    (3, "Directions", "後面", "behind"),
    (3, "Directions", "上面", "above"),
    (3, "Directions", "下面", "below"),
    (3, "Directions", "對面", "opposite"),
    (3, "Transport", "巴士", "bus"),
    (3, "Transport", "地鐵", "underground railway"),
    (3, "Transport", "的士", "taxi"),
    (3, "Transport", "火車", "train"),
    (3, "Transport", "飛機", "aeroplane"),
    (3, "Transport", "船", "boat / ship"),
    (3, "Daily Routine", "起身", "to get up"),
    (3, "Daily Routine", "瞓覺", "to sleep"),
    (3, "Daily Routine", "沖涼", "to take a shower"),
    (3, "Daily Routine", "返工", "to go to work"),
    (3, "Daily Routine", "放工", "to finish work"),
    (3, "Daily Routine", "食飯", "to have a meal"),
    (3, "Daily Routine", "洗手", "to wash one's hands"),
    (3, "Daily Routine", "換衫", "to change clothes"),
    (3, "Daily Routine", "出街", "to go out"),
    (3, "Daily Routine", "休息", "to rest"),
    # ------------------------------------------------------------------ Level 4
    (4, "Emotions", "開心", "happy"),
    (4, "Emotions", "傷心", "sad"),
    (4, "Emotions", "嬲", "angry", "nau1"),
    (4, "Emotions", "驚", "afraid", "geng1"),
    (4, "Emotions", "眼瞓", "sleepy"),
    (4, "Emotions", "緊張", "nervous"),
    (4, "Emotions", "興奮", "excited"),
    (4, "Work & Study", "工作", "work / job"),
    (4, "Work & Study", "返學", "to go to school"),
    (4, "Work & Study", "功課", "homework"),
    (4, "Work & Study", "考試", "exam"),
    (4, "Work & Study", "老師", "teacher"),
    (4, "Work & Study", "學生", "student"),
    (4, "Work & Study", "同事", "colleague"),
    (4, "Descriptions", "大", "big", "daai6"),
    (4, "Descriptions", "細", "small"),
    (4, "Descriptions", "高", "tall / high"),
    (4, "Descriptions", "矮", "short (in height)"),
    (4, "Descriptions", "靚", "pretty / good-looking", "leng3"),
    (4, "Descriptions", "快", "fast"),
    (4, "Descriptions", "慢", "slow"),
    (4, "Descriptions", "難", "difficult"),
    (4, "Communication", "電話", "telephone"),
    (4, "Communication", "打電話", "to make a phone call"),
    (4, "Communication", "短訊", "text message"),
    (4, "Communication", "電郵", "email"),
    (4, "Communication", "傾偈", "to chat"),
    (4, "Communication", "問", "to ask"),
    (4, "Communication", "答", "to answer"),
    (4, "Food Culture", "飲茶", "to go for dim sum"),
    (4, "Food Culture", "點心", "dim sum"),
    (4, "Food Culture", "燒賣", "siu mai dumpling"),
    (4, "Food Culture", "蝦餃", "prawn dumpling"),
    (4, "Food Culture", "奶茶", "milk tea"),
    (4, "Food Culture", "餐牌", "menu"),
    (4, "Connectives", "但係", "but"),
    (4, "Connectives", "因為", "because"),
    (4, "Connectives", "所以", "so / therefore"),
    (4, "Connectives", "如果", "if"),
    (4, "Connectives", "不過", "however"),
    (4, "Connectives", "同埋", "and / together with"),
    (4, "Connectives", "或者", "or / perhaps"),
    (4, "Connectives", "雖然", "although"),
    # ------------------------------------------------------------------ Level 5
    (5, "Abstract Nouns", "意見", "opinion"),
    (5, "Abstract Nouns", "經驗", "experience"),
    (5, "Abstract Nouns", "機會", "opportunity"),
    (5, "Abstract Nouns", "問題", "problem / question"),
    (5, "Abstract Nouns", "原因", "reason / cause"),
    (5, "Abstract Nouns", "結果", "result"),
    (5, "Abstract Nouns", "目標", "goal"),
    (5, "Society", "社會", "society"),
    (5, "Society", "政府", "government"),
    (5, "Society", "經濟", "economy"),
    (5, "Society", "文化", "culture"),
    (5, "Society", "環境", "environment"),
    (5, "Society", "新聞", "news"),
    (5, "Society", "歷史", "history"),
    (5, "Opinion & Modality", "應該", "should"),
    (5, "Opinion & Modality", "可能", "maybe / possible"),
    (5, "Opinion & Modality", "一定", "definitely"),
    (5, "Opinion & Modality", "好似", "to seem / to resemble"),
    (5, "Opinion & Modality", "覺得", "to feel / to think"),
    (5, "Opinion & Modality", "希望", "to hope"),
    (5, "Opinion & Modality", "需要", "to need"),
    (5, "Adverbs & Nuance", "特別", "especially / special"),
    (5, "Adverbs & Nuance", "突然", "suddenly"),
    (5, "Adverbs & Nuance", "差唔多", "almost / about the same"),
    (5, "Adverbs & Nuance", "至少", "at least"),
    (5, "Adverbs & Nuance", "已經", "already"),
    (5, "Adverbs & Nuance", "仍然", "still"),
    (5, "Adverbs & Nuance", "終於", "finally"),
    (5, "Useful Phrases", "你食咗飯未", "have you eaten yet?"),
    (5, "Useful Phrases", "唔使客氣", "you're welcome"),
    (5, "Useful Phrases", "慢慢嚟", "take it easy"),
    (5, "Useful Phrases", "加油", "keep it up!"),
    (5, "Useful Phrases", "冇所謂", "it doesn't matter"),
    (5, "Useful Phrases", "講笑", "to joke"),
    (5, "Useful Phrases", "小心", "be careful"),
    (5, "Useful Phrases", "得閒飲茶", "let's meet up sometime"),
    # ------------------------------------------------------------------ Level 6
    (6, "Idioms", "一石二鳥", "kill two birds with one stone"),
    (6, "Idioms", "半途而廢", "to give up halfway"),
    (6, "Idioms", "塞翁失馬", "a blessing in disguise"),
    (6, "Idioms", "一心一意", "wholeheartedly"),
    (6, "Idioms", "千方百計", "by every possible means"),
    (6, "Idioms", "自相矛盾", "to contradict oneself"),
    (6, "Idioms", "開門見山", "to get straight to the point"),
    (6, "Idioms", "井底之蛙", "a person of limited outlook"),
    (6, "Formal & Written", "實現", "to realise / to achieve"),
    (6, "Formal & Written", "發展", "to develop"),
    (6, "Formal & Written", "影響", "to influence / impact"),
    (6, "Formal & Written", "提供", "to provide"),
    (6, "Formal & Written", "建立", "to establish"),
    (6, "Formal & Written", "維持", "to maintain"),
    (6, "Formal & Written", "促進", "to promote / to further"),
    (6, "Discourse Markers", "換句話說", "in other words"),
    (6, "Discourse Markers", "由此可見", "from this it can be seen"),
    (6, "Discourse Markers", "值得注意", "worth noting"),
    (6, "Discourse Markers", "無論如何", "in any case"),
    (6, "Discourse Markers", "首先", "first of all"),
    (6, "Discourse Markers", "總之", "in short"),
    (6, "Discourse Markers", "相反", "on the contrary"),
    (6, "Advanced Slang", "論盡", "clumsy"),
    (6, "Advanced Slang", "大鑊", "big trouble"),
    (6, "Advanced Slang", "執生", "to improvise / play it by ear"),
    (6, "Advanced Slang", "心思思", "restlessly eager"),
    (6, "Advanced Slang", "無厘頭", "nonsensical / absurd"),
    (6, "Advanced Slang", "爆冷", "an upset / surprise result"),
]
